### ISSUE TITLE
How to get it running

### ISSUE THREAD

**Issue by ph4il** [Tyderion/AniDb-AniAdd-CLI#2]
Sorry for not seeing the obvious... but how do I get this even running? Do I have to compile it first? Can you please give a short explanation?

Any tip would be highly appreciated!

Thanks!

**Comment by runecalico** [comment]
I am in no way related to this project.
I was unable to find any prebuilt jar's of this project, so I had to compile it myself using Intellij.
I would expect you could use other programs like Visual Studio Code to compile it.

**Comment by Tyderion** [comment]
oh hi @ph4il  
I didn't even see this issue :(
I've made a release containing the a built jar of the current master https://github.com/Tyderion/AniDb-AniAdd-CLI/releases/tag/v.1.0-alpha

@runecalico  yeah, you're totally right, compiling works, but you need java 1.8
